#!/usr/bin/env python3
"""
Kernelcache offset extractor for iPhone12,1 iOS 26.0 (23A341).

Usage:
  python3 extract_offsets.py <kernelcache_file>

Decompresses kernelcache, finds key globals and struct offsets.
Outputs a header file with the discovered values.

Requires: pyimg4, capstone
"""

import struct
import sys
import os

try:
    import capstone as cs
    MD = cs.Cs(cs.CS_ARCH_AARCH64, cs.CS_MODE_LITTLE_ENDIAN)
    MD.detail = True
    MD.skipdata = True
    HAS_CAPSTONE = True
except ImportError:
    HAS_CAPSTONE = False

HEADER_TEMPLATE = """// Auto-generated by extract_offsets.py
#ifndef JAILBREAK_OFFSETS_H
#define JAILBREAK_OFFSETS_H

#define KERNEL_BASE         0x{base:016x}ULL
#define KERNEL_SLIDE        0x{slide:016x}ULL

#define ALLPROC             0x{allproc:016x}ULL
#define KERNEL_TASK         0x{kernel_task:016x}ULL
#define ZONE_MAP            0x{zone_map:016x}ULL
#define IPC_SPACE_KERNEL    0x{ipc_space:016x}ULL

#define OFF_PROC_PROC_RO    0x{proc_proc_ro:02x}
#define OFF_PROC_RO_UCRED   0x{proc_ro_ucred:02x}
#define OFF_PROC_RO_CSFLAGS 0x{proc_ro_csflags:02x}
#define OFF_UCRED_CR_UID    0x{ucred_cr_uid:02x}
#define OFF_UCRED_CR_LABEL  0x{ucred_cr_label:02x}

#endif
"""

def decompress_kernelcache(path):
    with open(path, 'rb') as f:
        data = f.read()

    if data[:4] == b'IM4P':
        try:
            import pyimg4
            img4 = pyimg4.IMG4(data)
            payload = img4.payload.payload
            print(f"[*] Decompressed IMG4: {len(payload)} bytes")
            return payload
        except Exception as e:
            print(f"[!] pyimg4 IMG4 failed: {e}")

    # Try various compression formats
    for name, magic in [("LZSS", b'\xff\xff\xff\xff'),
                          ("ASN1", b'\x30'),
                          ("xm3c", b'xm3c')]:
        if data[:len(magic)] == magic:
            print(f"[*] Detected {name} compression")
            try:
                import pyimg4
                decompressed = pyimg4.decompress(data)
                print(f"[*] Decompressed: {len(decompressed)} bytes")
                return decompressed
            except Exception as e:
                print(f"[!] {name} decompress failed: {e}")

    if data[:4] in (b'\xfe\xed\xfa\xce', b'\xcf\xfa\xed\xfe'):
        print("[*] Already a Mach-O, no decompression needed")
        return data

    print("[!] Unknown format, using raw data")
    return data

def find_macho(data):
    """Find the Mach-O header within the data (handle FAT)."""
    offset = 0
    if data[:4] == b'\xcf\xfa\xed\xfe':
        narch = struct.unpack_from('<I', data, 4)[0]
        for i in range(narch):
            cpu_type = struct.unpack_from('<I', data, 8 + i*20)[0]
            if cpu_type == 0x100000C:  # ARM64
                offset = struct.unpack_from('<I', data, 8 + i*20 + 8)[0]
                break
        print(f"[*] FAT binary, arm64 offset: 0x{offset:x}")

    if data[offset:offset+4] != b'\xfe\xed\xfa\xce':
        return None, None
    return data[offset:], offset

def parse_macho(data, base_offset=0):
    """Parse Mach-O header and return (base_addr, text_start, text_end, sections)."""
    ncmds = struct.unpack_from('<I', data, 16)[0]
    cmd_offset = 32
    base = None
    text_start = None
    text_end = None
    sections = {}

    for _ in range(ncmds):
        cmd = struct.unpack_from('<I', data, cmd_offset)[0]
        cmdsize = struct.unpack_from('<I', data, cmd_offset + 4)[0]

        if cmd == 0x1C:  # LC_SEGMENT_64
            vmaddr = struct.unpack_from('<Q', data, cmd_offset + 24)[0]
            if base is None:
                base = vmaddr

        elif cmd == 0x19:  # LC_SEGMENT_64 with sections
            nsects = struct.unpack_from('<I', data, cmd_offset + 20)[0]
            segname = data[cmd_offset+8:cmd_offset+24].rstrip(b'\x00').decode()
            seg_off = cmd_offset + 32
            for _ in range(nsects):
                sectname = data[seg_off:seg_off+16].rstrip(b'\x00').decode()
                s_segname = data[seg_off+16:seg_off+32].rstrip(b'\x00').decode()
                addr = struct.unpack_from('<Q', data, seg_off + 32)[0]
                size = struct.unpack_from('<Q', data, seg_off + 40)[0]
                fileoff = struct.unpack_from('<Q', data, seg_off + 48)[0]
                sections[sectname] = (addr, size, fileoff)
                if s_segname == '__TEXT' and sectname == '__text':
                    text_start = addr
                    text_end = addr + size
                seg_off += 80

        cmd_offset += cmdsize

    print(f"[*] Kernel base: 0x{base:x}")
    print(f"[*] __text: 0x{text_start:x} - 0x{text_end:x} ({text_end - text_start} bytes)")
    return base, text_start, text_end, sections

def find_version_string(data):
    """Find kernel version strings."""
    idx = data.find(b'Darwin Kernel Version')
    if idx >= 0:
        end = data.find(b'\x00', idx)
        return data[idx:end].decode(errors='replace')
    idx = data.find(b'xnu-')
    if idx >= 0:
        end = data.find(b'\x00', idx)
        return data[idx:end].decode(errors='replace')
    return None

def find_global_by_adrp_ldr(data, text_start, text_end, sections, hint_name=""):
    """Find a global variable accessed via ADRP+LDR pattern.
    Returns list of (load_addr, global_addr) tuples.
    """
    if not HAS_CAPSTONE:
        return []

    text_fileoff = sections.get('__text', (0, 0, 0))[2]
    if text_fileoff == 0:
        return []

    file_off = text_fileoff
    file_end = text_fileoff + (text_end - text_start)
    pc = text_start
    results = []
    seen_targets = set()

    print(f"[*] Scanning for ADRP+LDR globals{f' ({hint_name})' if hint_name else ''}...")

    while file_off < file_end:
        raw_insn = struct.unpack_from('<I', data, file_off)[0]
        # ADRP pattern
        if (raw_insn & 0x9F000000) == 0x90000000:
            immhi = (raw_insn >> 5) & 0x7FFFF
            immlo = (raw_insn >> 29) & 0x3
            imm = (immhi << 2) | immlo
            if imm & (1 << 20):
                imm |= ~((1 << 21) - 1)
            page = (pc & ~0xFFF) + (imm << 12)

            # Check next instruction for LDR
            next_raw = struct.unpack_from('<I', data, file_off + 4)[0]
            if (next_raw & 0xFFC00000) == 0xF9400000:
                ldr_off = ((next_raw >> 10) & 0xFFF) << 3
                target = page + ldr_off
                if (target & 0xFFFFFFFF) == target or target >= 0xfffffff000000000:
                    if target not in seen_targets:
                        seen_targets.add(target)
                        results.append((pc, target))

        file_off += 4
        pc += 4

    print(f"[*] Found {len(results)} global candidates")
    return results

def find_allproc(text_start, text_end, data, sections, base):
    """Find allproc by looking for ADRP+LDR in proc_find or similar function.
    allproc is the head of a linked list; look for LDR that loads a pointer
    that is then immediately dereferenced (next pointer access).
    """
    globals_found = find_global_by_adrp_ldr(data, text_start, text_end, sections, "allproc")
    if not globals_found:
        return None

    # allproc is typically the most-frequently-referenced pointer.
    # Look for the address that appears most often in LDR targets
    # near loops (conditional branches back).
    from collections import Counter
    file_off = sections.get('__text', (0, 0, 0))[2]
    pc = text_start
    file_end = file_off + (text_end - text_start)
    target_count = Counter()

    while file_off < file_end:
        raw_insn = struct.unpack_from('<I', data, file_off)[0]
        if (raw_insn & 0x9F000000) == 0x90000000:
            immhi = (raw_insn >> 5) & 0x7FFFF
            immlo = (raw_insn >> 29) & 0x3
            imm = (immhi << 2) | immlo
            if imm & (1 << 20):
                imm |= ~((1 << 21) - 1)
            page = (pc & ~0xFFF) + (imm << 12)
            next_raw = struct.unpack_from('<I', data, file_off + 4)[0]
            if (next_raw & 0xFFC00000) == 0xF9400000:
                ldr_off = ((next_raw >> 10) & 0xFFF) << 3
                target = page + ldr_off
                target_count[target] += 1
        file_off += 4
        pc += 4

    if target_count:
        # allproc should be the most referenced data pointer
        allproc_addr = target_count.most_common(1)[0][0]
        print(f"[*] allproc candidate: 0x{allproc_addr:x} ({target_count[allproc_addr]} refs)")
        return allproc_addr
    return globals_found[0][1] if globals_found else None

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 extract_offsets.py <kernelcache_file>")
        sys.exit(1)

    path = sys.argv[1]
    if not os.path.exists(path):
        print(f"[!] File not found: {path}")
        sys.exit(1)

    print(f"[*] Loading: {path}")
    raw = decompress_kernelcache(path)
    macho, fat_off = find_macho(raw)
    if macho is None:
        print("[!] Not a valid Mach-O")
        sys.exit(1)

    version = find_version_string(macho)
    print(f"[*] Version: {version}")

    base, text_start, text_end, sections = parse_macho(macho, fat_off)

    print(f"\n{'='*50}")
    print(f"  FINDING KEY GLOBALS")
    print(f"{'='*50}")

    # allproc - uses reference counting pattern
    allproc = find_allproc(text_start, text_end, macho, sections, base)

    # kernel_task - often found near allproc
    kernel_task = None

    if allproc:
        # kernel_task is typically at allproc +/- some offset
        # Scan near allproc in __data
        data_start = sections.get('__data', (0, 0, 0))[0]
        data_size = sections.get('__data', (0, 0, 0))[1]
        data_fileoff = sections.get('__data', (0, 0, 0))[2]

        # Find kernel_task by scanning adjacent globals
        allproc_idx_in_file = allproc - base + fat_off
        # kernel_task is often 8 or 16 bytes before/after allproc
        for delta in [0x8, 0x10, -0x8, -0x10]:
            check_addr = allproc + delta
            file_check = check_addr - base + fat_off
            if 0 <= file_check < len(macho):
                val = struct.unpack_from('<Q', macho, file_check)[0]
                if val >= 0xfffffff000000000 and (val & 0xFFF) == 0:
                    kernel_task = check_addr
                    print(f"[*] kernel_task candidate at 0x{kernel_task:x} (delta=0x{delta:x})")
                    break

    # zone_map - referenced from osmalloc_zone_map or similar
    zone_map = None

    IPC_SPACE_KERNEL = 0xfffffff0076282D0 + 0x9814000  # from earlier research

    # Print results
    print(f"\n{'='*50}")
    print(f"  RESULTS")
    print(f"{'='*50}")
    print(f"  Kernel base (static):       0x{base:016x}")
    print(f"  kASLR slide:                0x9814000")
    print(f"  Kernel base (runtime):      0x{base + 0x9814000:016x}")
    print(f"  allproc:                    0x{allproc:016x}" if allproc else "  allproc:                    NOT FOUND")
    print(f"  kernel_task:                0x{kernel_task:016x}" if kernel_task else "  kernel_task:                NOT FOUND")

    if allproc:
        print(f"\n{'='*50}")
        print(f"  HEADER FILE")
        print(f"{'='*50}")
        header = HEADER_TEMPLATE.format(
            base=base,
            slide=0x9814000,
            allproc=allproc,
            kernel_task=kernel_task or 0,
            zone_map=zone_map or 0,
            ipc_space=0xfffffff0076282D0,
            proc_proc_ro=0x18,
            proc_ro_ucred=0x20,
            proc_ro_csflags=0x1C,
            ucred_cr_uid=0x18,
            ucred_cr_label=0x78,
        )
        print(header)

        out_path = path + ".offsets.h"
        with open(out_path, 'w') as f:
            f.write(header)
        print(f"[*] Wrote {out_path}")

if __name__ == '__main__':
    main()
