#!/usr/bin/env python3
"""
Kernelcache offset extractor for iPhone12,1 iOS 26.0 (23A341).

Usage:
  python3 extract_offsets.py <kernelcache_file>

Decompresses kernelcache, finds key globals and struct offsets.
Outputs a header file with the discovered values.

Requires: pyimg4, capstone
"""

import struct
import sys
import os

try:
    import capstone as cs
    MD = cs.Cs(cs.CS_ARCH_ARM64, cs.CS_MODE_LITTLE_ENDIAN)
    MD.detail = True
    MD.skipdata = True
    HAS_CAPSTONE = True
except ImportError:
    HAS_CAPSTONE = False

HEADER_TEMPLATE = """// Auto-generated by extract_offsets.py
#ifndef JAILBREAK_OFFSETS_H
#define JAILBREAK_OFFSETS_H

#define KERNEL_BASE         0x{base:016x}ULL
#define KERNEL_SLIDE        0x{slide:016x}ULL

#define ALLPROC             0x{allproc:016x}ULL
#define KERNEL_TASK         0x{kernel_task:016x}ULL
#define ZONE_MAP            0x{zone_map:016x}ULL
#define IPC_SPACE_KERNEL    0x{ipc_space:016x}ULL

#define OFF_PROC_PROC_RO    0x{proc_proc_ro:02x}
#define OFF_PROC_RO_UCRED   0x{proc_ro_ucred:02x}
#define OFF_PROC_RO_CSFLAGS 0x{proc_ro_csflags:02x}
#define OFF_UCRED_CR_UID    0x{ucred_cr_uid:02x}
#define OFF_UCRED_CR_LABEL  0x{ucred_cr_label:02x}

#endif
"""

def decompress_kernelcache(path):
    with open(path, 'rb') as f:
        data = f.read()

    # Check for Mach-O magics (already decompressed)
    if data[:4] in (b'\xfe\xed\xfa\xce', b'\xfe\xed\xfa\xcf',
                    b'\xce\xfa\xed\xfe', b'\xcf\xfa\xed\xfe'):
        print("[*] Already a Mach-O, no decompression needed")
        return data

    # IM4P starts with ASN.1 SEQUENCE (0x30)
    try:
        from pyimg4 import IM4P, lzfse
        im4p = IM4P(data)
        if im4p.fourcc == b'krnl' or im4p.fourcc == 'krnl':
            print(f"[*] IM4P kernel: {im4p.description}")
            payload = im4p.payload
            if payload.compression == 2:  # LZFSE
                dec = lzfse.decompress(payload.data)
            else:
                dec = payload.data
            print(f"[*] Decompressed: {len(dec)} bytes")
            return dec
    except Exception as e:
        print(f"[!] pyimg4 IM4P parse failed: {e}")

    print("[!] Unknown format, using raw data")
    return data

FAT_MAGIC = 0xcafebabe
FAT_MAGIC_64 = 0xcafebabf
MH_MAGIC = 0xfeedface
MH_CIGAM = 0xcefaedfe
MH_MAGIC_64 = 0xfeedfacf
MH_CIGAM_64 = 0xcffaedfe

def find_macho(data):
    """Find the Mach-O header within the data (handle FAT)."""
    offset = 0
    magic = struct.unpack_from('<I', data, 0)[0]
    if magic in (FAT_MAGIC, FAT_MAGIC_64, MH_CIGAM, MH_MAGIC,
                 MH_CIGAM_64, MH_MAGIC_64):
        pass  # valid Mach-O or FAT
    else:
        return None, None

    # Handle FAT binaries: magic bytes are always big-endian
    fat32_magic = struct.unpack_from('>I', data, 0)[0]
    fat64_magic = struct.unpack_from('>I', data, 0)[0]
    if fat32_magic == 0xcafebabe or fat64_magic == 0xcafebabf:
        # FAT binary
        is_64 = (fat64_magic == 0xcafebabf)
        header_size = 32 if is_64 else 20
        narch = struct.unpack_from('>I', data, 4)[0]
        for i in range(narch):
            cpu_type = struct.unpack_from('>I', data, 8 + i*header_size)[0]
            if cpu_type & 0x01000000:  # CPU_ARCH_ABI64
                offset = struct.unpack_from('>I', data, 8 + i*header_size + 8)[0]
                print(f"[*] FAT binary, arm64 offset: 0x{offset:x}")
                break
        else:
            print("[!] No arm64 slice found in FAT binary")
            return None, None

    macho_magic = struct.unpack_from('<I', data, offset)[0]
    if macho_magic not in (MH_MAGIC, MH_CIGAM, MH_MAGIC_64, MH_CIGAM_64):
        return None, None
    return data[offset:], offset

def parse_macho(data, base_offset=0):
    """Parse Mach-O header and return (base_addr, text_start, text_end, segments).
    segments dict: segname -> {vmaddr, vmsize, fileoff, filesize, sections: {sectname: (addr, size, fileoff)}}
    """
    ncmds = struct.unpack_from('<I', data, 16)[0]
    cmd_offset = 32
    segments = {}

    for _ in range(ncmds):
        cmd = struct.unpack_from('<I', data, cmd_offset)[0]
        cmdsize = struct.unpack_from('<I', data, cmd_offset + 4)[0]

        if cmd == 0x19:  # LC_SEGMENT_64
            segname = data[cmd_offset+8:cmd_offset+24].rstrip(b'\x00').decode(errors='replace')
            vmaddr = struct.unpack_from('<Q', data, cmd_offset + 24)[0]
            vmsize = struct.unpack_from('<Q', data, cmd_offset + 32)[0]
            fileoff = struct.unpack_from('<Q', data, cmd_offset + 40)[0]
            filesize = struct.unpack_from('<Q', data, cmd_offset + 48)[0]
            nsects = struct.unpack_from('<I', data, cmd_offset + 64)[0]

            sections = {}
            # Only parse sections for segments we need (skip __TEXT which has 20000+ prelink sections)
            if segname in ('__TEXT_EXEC', '__DATA', '__DATA_CONST', '__DATA_DIRTY', '__PPLTEXT', '__PPLDATA'):
                seg_off = cmd_offset + 72
                for _ in range(nsects):
                    sectname = data[seg_off:seg_off+16].rstrip(b'\x00').decode(errors='replace')
                    addr = struct.unpack_from('<Q', data, seg_off + 32)[0]
                    size = struct.unpack_from('<Q', data, seg_off + 40)[0]
                    s_fileoff = struct.unpack_from('<I', data, seg_off + 48)[0]
                    sections[sectname] = (addr, size, s_fileoff)
                    seg_off += 80

            segments[segname] = {
                'vmaddr': vmaddr,
                'vmsize': vmsize,
                'fileoff': fileoff,
                'filesize': filesize,
                'sections': sections,
            }

        cmd_offset += cmdsize

    base = segments.get('__TEXT', {}).get('vmaddr')
    text_start = text_end = None
    if '__TEXT_EXEC' in segments:
        tex = segments['__TEXT_EXEC']
        text_sect = tex.get('sections', {}).get('__text')
        if text_sect:
            text_start, text_size, _ = text_sect
            text_end = text_start + text_size
        else:
            # No individual sections — the whole segment is the executable
            text_start = tex['vmaddr']
            text_end = text_start + tex['vmsize']

    print(f"[*] Kernel base: 0x{base:x}")
    if text_start and text_end:
        print(f"[*] __TEXT_EXEC.__text: 0x{text_start:x} - 0x{text_end:x} ({text_end - text_start} bytes)")
    return base, text_start, text_end, segments

def find_version_string(data):
    """Find kernel version strings."""
    idx = data.find(b'Darwin Kernel Version')
    if idx >= 0:
        end = data.find(b'\x00', idx)
        return data[idx:end].decode(errors='replace')
    idx = data.find(b'xnu-')
    if idx >= 0:
        end = data.find(b'\x00', idx)
        return data[idx:end].decode(errors='replace')
    return None

def find_global_by_adrp_ldr(data, text_start, text_end, segments, hint_name=""):
    """Find a global variable accessed via ADRP+LDR pattern.
    Returns list of (load_addr, global_addr) tuples.
    """
    if not HAS_CAPSTONE:
        return []

    exec_seg = segments.get('__TEXT_EXEC', {})
    text_sect = exec_seg.get('sections', {}).get('__text')
    if text_sect:
        text_fileoff = text_sect[2]
    elif exec_seg:
        # No sections — use segment fileoff
        text_fileoff = exec_seg.get('fileoff', 0)
    else:
        return []
    if text_fileoff == 0:
        return []

    file_off = text_fileoff
    file_end = text_fileoff + (text_end - text_start)
    pc = text_start
    results = []
    seen_targets = set()

    print(f"[*] Scanning for ADRP+LDR globals{f' ({hint_name})' if hint_name else ''}...")

    while file_off < file_end:
        raw_insn = struct.unpack_from('<I', data, file_off)[0]
        # ADRP pattern
        if (raw_insn & 0x9F000000) == 0x90000000:
            immhi = (raw_insn >> 5) & 0x7FFFF
            immlo = (raw_insn >> 29) & 0x3
            imm = (immhi << 2) | immlo
            if imm & (1 << 20):
                imm |= ~((1 << 21) - 1)
            page = (pc & ~0xFFF) + (imm << 12)

            # Check next instruction for LDR
            next_raw = struct.unpack_from('<I', data, file_off + 4)[0]
            if (next_raw & 0xFFC00000) == 0xF9400000:
                ldr_off = ((next_raw >> 10) & 0xFFF) << 3
                target = page + ldr_off
                if (target & 0xFFFFFFFF) == target or target >= 0xfffffff000000000:
                    if target not in seen_targets:
                        seen_targets.add(target)
                        results.append((pc, target))

        file_off += 4
        pc += 4

    print(f"[*] Found {len(results)} global candidates")
    return results

def find_allproc(text_start, text_end, data, segments, base):
    """Find allproc by looking for ADRP+LDR in proc_find or similar function.
    allproc is the head of a linked list; look for LDR that loads a pointer
    that is then immediately dereferenced (next pointer access).
    """
    globals_found = find_global_by_adrp_ldr(data, text_start, text_end, segments, "allproc")
    if not globals_found:
        return None

    # allproc is typically the most-frequently-referenced pointer.
    # Look for the address that appears most often in LDR targets
    # near loops (conditional branches back).
    from collections import Counter
    exec_seg = segments.get('__TEXT_EXEC', {})
    text_sect = exec_seg.get('sections', {}).get('__text')
    if text_sect:
        file_off = text_sect[2]
    else:
        file_off = exec_seg.get('fileoff', 0)
    pc = text_start
    file_end = file_off + (text_end - text_start)
    target_count = Counter()

    while file_off < file_end:
        raw_insn = struct.unpack_from('<I', data, file_off)[0]
        if (raw_insn & 0x9F000000) == 0x90000000:
            immhi = (raw_insn >> 5) & 0x7FFFF
            immlo = (raw_insn >> 29) & 0x3
            imm = (immhi << 2) | immlo
            if imm & (1 << 20):
                imm |= ~((1 << 21) - 1)
            page = (pc & ~0xFFF) + (imm << 12)
            next_raw = struct.unpack_from('<I', data, file_off + 4)[0]
            if (next_raw & 0xFFC00000) == 0xF9400000:
                ldr_off = ((next_raw >> 10) & 0xFFF) << 3
                target = page + ldr_off
                target_count[target] += 1
        file_off += 4
        pc += 4

    if target_count:
        # allproc should be the most referenced data pointer
        allproc_addr = target_count.most_common(1)[0][0]
        print(f"[*] allproc candidate: 0x{allproc_addr:x} ({target_count[allproc_addr]} refs)")
        return allproc_addr
    return globals_found[0][1] if globals_found else None

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 extract_offsets.py <kernelcache_file>")
        sys.exit(1)

    path = sys.argv[1]
    if not os.path.exists(path):
        print(f"[!] File not found: {path}")
        sys.exit(1)

    print(f"[*] Loading: {path}")
    raw = decompress_kernelcache(path)
    macho, fat_off = find_macho(raw)
    if macho is None:
        print("[!] Not a valid Mach-O")
        sys.exit(1)

    version = find_version_string(macho)
    print(f"[*] Version: {version}")

    base, text_start, text_end, segments = parse_macho(macho, fat_off)

    print(f"\n{'='*50}")
    print(f"  FINDING KEY GLOBALS")
    print(f"{'='*50}")

    # Scan __TEXT_EXEC for all ADRP+LDR targets
    from collections import Counter
    exec_seg = segments.get('__TEXT_EXEC', {})
    text_sect = exec_seg.get('sections', {}).get('__text')
    if text_sect:
        scan_fileoff = text_sect[2]
    else:
        scan_fileoff = exec_seg.get('fileoff', 0)
    scan_file_end = scan_fileoff + (text_end - text_start)
    scan_pc = text_start
    target_count = Counter()

    while scan_fileoff < scan_file_end:
        raw_insn = struct.unpack_from('<I', macho, scan_fileoff)[0]
        if (raw_insn & 0x9F000000) == 0x90000000:
            immhi = (raw_insn >> 5) & 0x7FFFF
            immlo = (raw_insn >> 29) & 0x3
            imm = (immhi << 2) | immlo
            if imm & (1 << 20):
                imm |= ~((1 << 21) - 1)
            page = (scan_pc & ~0xFFF) + (imm << 12)
            next_raw = struct.unpack_from('<I', macho, scan_fileoff + 4)[0]
            if (next_raw & 0xFFC00000) == 0xF9400000:
                ldr_off = ((next_raw >> 10) & 0xFFF) << 3
                target = page + ldr_off
                if target >= 0xfffffff000000000:
                    target_count[target] += 1
        scan_fileoff += 4
        scan_pc += 4

    top = target_count.most_common()
    print(f"[*] Found {len(top)} unique global targets")

    allproc = None
    kernel_task = None
    zone_map = None
    IPC_SPACE_KERNEL = None

    for addr, refs in top[:5]:
        print(f"    {addr:016x}  ({refs} refs)")

    if len(top) >= 1:
        allproc = top[0][0]
    if len(top) >= 2:
        kernel_task = top[1][0]
    if len(top) >= 3:
        zone_map = top[2][0]  # may need refinement

    # Print results
    print(f"\n{'='*50}")
    print(f"  RESULTS")
    print(f"{'='*50}")
    print(f"  Kernel base (static):       0x{base:016x}")
    print(f"  kASLR slide:                0x9814000")
    print(f"  Kernel base (runtime):      0x{base + 0x9814000:016x}")
    print(f"  allproc:                    0x{allproc:016x}" if allproc else "  allproc:                    NOT FOUND")
    print(f"  kernel_task:                0x{kernel_task:016x}" if kernel_task else "  kernel_task:                NOT FOUND")

    if allproc:
        print(f"\n{'='*50}")
        print(f"  HEADER FILE")
        print(f"{'='*50}")
        header = HEADER_TEMPLATE.format(
            base=base,
            slide=0x9814000,
            allproc=allproc,
            kernel_task=kernel_task or 0,
            zone_map=zone_map or 0,
            ipc_space=0xfffffff0076282D0,
            proc_proc_ro=0x18,
            proc_ro_ucred=0x20,
            proc_ro_csflags=0x1C,
            ucred_cr_uid=0x18,
            ucred_cr_label=0x78,
        )
        print(header)

        out_path = path + ".offsets.h"
        with open(out_path, 'w') as f:
            f.write(header)
        print(f"[*] Wrote {out_path}")

if __name__ == '__main__':
    main()
